/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

/**
 *
 * @author joaoPC
 */
public class TelaEfetuarPedido extends javax.swing.JFrame {

    /**
     * Creates new form TelaEfetuarPedido
     */
    public TelaEfetuarPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jLEfetuarPedido = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jBEfetuarPEfetuar = new javax.swing.JButton();
        jBEfetuarPCancelar = new javax.swing.JButton();
        jLEfetuarPNomeCliente = new javax.swing.JLabel();
        jLEfetuarPDataPedido = new javax.swing.JLabel();
        jLEfetuarPId = new javax.swing.JLabel();
        jLEfetuarPFormaPagamento = new javax.swing.JLabel();
        jBEfeturarPAddItemPedido = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jRBEfetuarPFormaPCartao = new javax.swing.JRadioButton();
        jRBEfetuarPFormaPCheque = new javax.swing.JRadioButton();
        jRBEfetuarPFormaPDinheiro = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLEfetuarPedido.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLEfetuarPedido.setText("Efetuar Pedido");

        jBEfetuarPEfetuar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBEfetuarPEfetuar.setText("Efetuar");
        jBEfetuarPEfetuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEfetuarPEfetuarActionPerformed(evt);
            }
        });

        jBEfetuarPCancelar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBEfetuarPCancelar.setText("Cancelar");
        jBEfetuarPCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEfetuarPCancelarActionPerformed(evt);
            }
        });

        jLEfetuarPNomeCliente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLEfetuarPNomeCliente.setText("Nome do Cliente:");

        jLEfetuarPDataPedido.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLEfetuarPDataPedido.setText("Data do pedido:");

        jLEfetuarPId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLEfetuarPId.setText("ID:");

        jLEfetuarPFormaPagamento.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLEfetuarPFormaPagamento.setText("Forma de pagamento:");

        jBEfeturarPAddItemPedido.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBEfeturarPAddItemPedido.setText("Adicionar um item ao pedido");
        jBEfeturarPAddItemPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEfeturarPAddItemPedidoActionPerformed(evt);
            }
        });

        jRBEfetuarPFormaPCartao.setText("Cartão");
        jRBEfetuarPFormaPCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBEfetuarPFormaPCartaoActionPerformed(evt);
            }
        });

        jRBEfetuarPFormaPCheque.setText("Cheque");
        jRBEfetuarPFormaPCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBEfetuarPFormaPChequeActionPerformed(evt);
            }
        });

        jRBEfetuarPFormaPDinheiro.setText("Dinheiro");
        jRBEfetuarPFormaPDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBEfetuarPFormaPDinheiroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLEfetuarPedido)
                        .addContainerGap(195, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRBEfetuarPFormaPDinheiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRBEfetuarPFormaPCartao)
                        .addGap(47, 47, 47)
                        .addComponent(jRBEfetuarPFormaPCheque)
                        .addGap(190, 190, 190))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLEfetuarPNomeCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLEfetuarPDataPedido)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLEfetuarPId)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLEfetuarPFormaPagamento)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBEfeturarPAddItemPedido)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBEfetuarPEfetuar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBEfetuarPCancelar)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLEfetuarPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLEfetuarPNomeCliente)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEfetuarPDataPedido)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLEfetuarPId)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLEfetuarPFormaPagamento)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRBEfetuarPFormaPCartao)
                        .addComponent(jRBEfetuarPFormaPCheque))
                    .addComponent(jRBEfetuarPFormaPDinheiro))
                .addGap(18, 18, 18)
                .addComponent(jBEfeturarPAddItemPedido)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEfetuarPEfetuar)
                    .addComponent(jBEfetuarPCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBEfetuarPEfetuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEfetuarPEfetuarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBEfetuarPEfetuarActionPerformed

    private void jBEfetuarPCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEfetuarPCancelarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jBEfetuarPCancelarActionPerformed

    private void jBEfeturarPAddItemPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEfeturarPAddItemPedidoActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_jBEfeturarPAddItemPedidoActionPerformed

    private void jRBEfetuarPFormaPCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBEfetuarPFormaPCartaoActionPerformed
          System.out.println("Icone está selecionado? "+jRBEfetuarPFormaPCartao.isSelected());    
       
        if(jRBEfetuarPFormaPCartao.isSelected()==true){
            jRBEfetuarPFormaPCheque.setSelected(false);
            jRBEfetuarPFormaPDinheiro.setSelected(false);
        }
    }//GEN-LAST:event_jRBEfetuarPFormaPCartaoActionPerformed

    private void jRBEfetuarPFormaPDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBEfetuarPFormaPDinheiroActionPerformed
        System.out.println("Icone está selecionado? "+jRBEfetuarPFormaPDinheiro.isSelected());    
       
        if(jRBEfetuarPFormaPDinheiro.isSelected()==true){
            jRBEfetuarPFormaPCheque.setSelected(false);
            jRBEfetuarPFormaPCartao.setSelected(false);
        }
            
    }//GEN-LAST:event_jRBEfetuarPFormaPDinheiroActionPerformed

    private void jRBEfetuarPFormaPChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBEfetuarPFormaPChequeActionPerformed
       System.out.println("Icone está selecionado? "+jRBEfetuarPFormaPCheque.isSelected());    
       
        if(jRBEfetuarPFormaPCheque.isSelected()==true){
            jRBEfetuarPFormaPDinheiro.setSelected(false);
            jRBEfetuarPFormaPCartao.setSelected(false);
        }
    }//GEN-LAST:event_jRBEfetuarPFormaPChequeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEfetuarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEfetuarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEfetuarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEfetuarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEfetuarPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jBEfetuarPCancelar;
    private javax.swing.JButton jBEfetuarPEfetuar;
    private javax.swing.JButton jBEfeturarPAddItemPedido;
    private javax.swing.JLabel jLEfetuarPDataPedido;
    private javax.swing.JLabel jLEfetuarPFormaPagamento;
    private javax.swing.JLabel jLEfetuarPId;
    private javax.swing.JLabel jLEfetuarPNomeCliente;
    private javax.swing.JLabel jLEfetuarPedido;
    private javax.swing.JRadioButton jRBEfetuarPFormaPCartao;
    private javax.swing.JRadioButton jRBEfetuarPFormaPCheque;
    private javax.swing.JRadioButton jRBEfetuarPFormaPDinheiro;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
